### ISSUE TITLE
[Accounts Exception] contact_infos#create (ActiveRecord::StatementInvalid)

### ISSUE THREAD

**Issue by karenc** [openstax/accounts#194]
```
ActionView::Template::Error: can't dup Symbol

  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_dispatch/http/parameter_filter.rb:40:in `dup'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_dispatch/http/parameter_filter.rb:40:in `block (2 levels) in compiled_filter'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_dispatch/http/parameter_filter.rb:32:in `each'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_dispatch/http/parameter_filter.rb:32:in `block in compiled_filter'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_dispatch/http/parameter_filter.rb:11:in `call'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_dispatch/http/parameter_filter.rb:11:in `filter'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_dispatch/http/parameter_filter.rb:36:in `block (2 levels) in compiled_filter'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_dispatch/http/parameter_filter.rb:32:in `each'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_dispatch/http/parameter_filter.rb:32:in `block in compiled_filter'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_dispatch/http/parameter_filter.rb:11:in `call'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_dispatch/http/parameter_filter.rb:11:in `filter'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_dispatch/http/filter_parameters.rb:36:in `filtered_env'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/exception_notification-4.0.1/lib/exception_notifier/views/exception_notifier/_environment.text.erb:1:in `_vendor_bundle_ruby_______gems_exception_notification_______lib_exception_notifier_views_exception_notifier__environment_text_erb___1017512073181975793_47899460'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_view/template.rb:145:in `block in render'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.17/lib/active_support/notifications.rb:125:in `instrument'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_view/template.rb:143:in `render'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_view/renderer/partial_renderer.rb:265:in `render_partial'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_view/renderer/partial_renderer.rb:238:in `block in render'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_view/renderer/abstract_renderer.rb:38:in `block in instrument'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.17/lib/active_support/notifications.rb:125:in `instrument'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_view/renderer/abstract_renderer.rb:38:in `instrument'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_view/renderer/partial_renderer.rb:237:in `render'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_view/renderer/renderer.rb:41:in `render_partial'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_view/helpers/rendering_helper.rb:27:in `render'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/exception_notification-4.0.1/lib/exception_notifier/views/exception_notifier/exception_notification.text.erb:9:in `block in _vendor_bundle_ruby_______gems_exception_notification_______lib_exception_notifier_views_exception_notifier_exception_notification_text_erb__1720159858895773560_48080540'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/exception_notification-4.0.1/lib/exception_notifier/views/exception_notifier/exception_notification.text.erb:7:in `map'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/exception_notification-4.0.1/lib/exception_notifier/views/exception_notifier/exception_notification.text.erb:7:in `_vendor_bundle_ruby_______gems_exception_notification_______lib_exception_notifier_views_exception_notifier_exception_notification_text_erb__1720159858895773560_48080540'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_view/template.rb:145:in `block in render'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.17/lib/active_support/notifications.rb:125:in `instrument'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_view/template.rb:143:in `render'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_view/renderer/template_renderer.rb:47:in `block (2 levels) in render_template'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_view/renderer/abstract_renderer.rb:38:in `block in instrument'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.17/lib/active_support/notifications.rb:125:in `instrument'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_view/renderer/abstract_renderer.rb:38:in `instrument'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_view/renderer/template_renderer.rb:46:in `block in render_template'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_view/renderer/template_renderer.rb:54:in `render_with_layout'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_view/renderer/template_renderer.rb:45:in `render_template'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_view/renderer/template_renderer.rb:18:in `render'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_view/renderer/renderer.rb:36:in `render_template'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_view/renderer/renderer.rb:17:in `render'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/abstract_controller/rendering.rb:110:in `_render_template'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/abstract_controller/rendering.rb:103:in `render_to_body'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/abstract_controller/rendering.rb:88:in `render'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/actionmailer-3.2.17/lib/action_mailer/base.rb:696:in `block in collect_responses_and_parts_order'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/actionmailer-3.2.17/lib/action_mailer/collector.rb:26:in `call'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/actionmailer-3.2.17/lib/action_mailer/collector.rb:26:in `custom'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/abstract_controller/collector.rb:10:in `text'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/exception_notification-4.0.1/lib/exception_notifier/email_notifier.rb:104:in `block in compose_email'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/actionmailer-3.2.17/lib/action_mailer/base.rb:697:in `collect_responses_and_parts_order'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/actionmailer-3.2.17/lib/action_mailer/base.rb:648:in `mail'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/exception_notification-4.0.1/lib/exception_notifier/email_notifier.rb:103:in `compose_email'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/exception_notification-4.0.1/lib/exception_notifier/email_notifier.rb:35:in `exception_notification'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/abstract_controller/base.rb:167:in `process_action'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/abstract_controller/base.rb:121:in `process'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/abstract_controller/rendering.rb:45:in `process'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/actionmailer-3.2.17/lib/action_mailer/base.rb:459:in `process'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/actionmailer-3.2.17/lib/action_mailer/base.rb:453:in `initialize'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/actionmailer-3.2.17/lib/action_mailer/base.rb:439:in `new'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/actionmailer-3.2.17/lib/action_mailer/base.rb:439:in `method_missing'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/exception_notification-4.0.1/lib/exception_notifier/email_notifier.rb:155:in `create_email'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/exception_notification-4.0.1/lib/exception_notifier/email_notifier.rb:146:in `call'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/exception_notification-4.0.1/lib/exception_notifier.rb:90:in `fire_notification'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/exception_notification-4.0.1/lib/exception_notifier.rb:35:in `block in notify_exception'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/exception_notification-4.0.1/lib/exception_notifier.rb:34:in `each'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/exception_notification-4.0.1/lib/exception_notifier.rb:34:in `notify_exception'
  /home/ostaccounts/src/accounts-61f3c16/config/initializers/controllers.rb:83:in `rescue_from_exception'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.17/lib/active_support/rescuable.rb:80:in `call'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.17/lib/active_support/rescuable.rb:80:in `rescue_with_handler'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_controller/metal/rescue.rb:15:in `rescue_with_handler'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_controller/metal/rescue.rb:32:in `rescue in process_action'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_controller/metal/rescue.rb:29:in `process_action'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.17/lib/active_support/notifications.rb:123:in `block in instrument'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.17/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.17/lib/active_support/notifications.rb:123:in `instrument'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_controller/metal/instrumentation.rb:29:in `process_action'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_controller/metal/params_wrapper.rb:207:in `process_action'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.17/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/abstract_controller/base.rb:121:in `process'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/abstract_controller/rendering.rb:45:in `process'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_controller/metal.rb:203:in `dispatch'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_controller/metal.rb:246:in `block in action'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_dispatch/routing/route_set.rb:73:in `call'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_dispatch/routing/route_set.rb:36:in `call'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/journey-1.0.4/lib/journey/router.rb:68:in `block in call'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/journey-1.0.4/lib/journey/router.rb:56:in `each'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/journey-1.0.4/lib/journey/router.rb:56:in `call'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_dispatch/routing/route_set.rb:608:in `call'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/apipie-rails-0.1.3/lib/apipie/static_dispatcher.rb:65:in `call'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:404:in `call_app!'
  /home/ostaccounts/src/accounts-61f3c16/lib/omniauth/strategies/custom_identity.rb:49:in `other_phase'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:185:in `call!'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:164:in `call'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:186:in `call!'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:164:in `call'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:186:in `call!'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:164:in `call'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:186:in `call!'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:164:in `call'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/omniauth-1.2.2/lib/omniauth/builder.rb:59:in `call'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/exception_notification-4.0.1/lib/exception_notification/rack.rb:28:in `call'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/rack-1.4.5/lib/rack/etag.rb:23:in `call'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/rack-1.4.5/lib/rack/conditionalget.rb:35:in `call'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_dispatch/middleware/head.rb:14:in `call'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_dispatch/middleware/params_parser.rb:21:in `call'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_dispatch/middleware/flash.rb:242:in `call'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/rack-1.4.5/lib/rack/session/abstract/id.rb:210:in `context'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/rack-1.4.5/lib/rack/session/abstract/id.rb:205:in `call'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_dispatch/middleware/cookies.rb:341:in `call'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.17/lib/active_record/query_cache.rb:64:in `call'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.17/lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in `call'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.17/lib/active_support/callbacks.rb:405:in `_run__2242247173160618525__call__1501331916882253353__callbacks'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.17/lib/active_support/callbacks.rb:405:in `__run_callback'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.17/lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.17/lib/active_support/callbacks.rb:81:in `run_callbacks'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/lograge-0.3.0/lib/lograge/rails_ext/rack/logger.rb:15:in `call_app'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/railties-3.2.17/lib/rails/rack/logger.rb:16:in `block in call'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.17/lib/active_support/tagged_logging.rb:22:in `tagged'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/railties-3.2.17/lib/rails/rack/logger.rb:16:in `call'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/quiet_assets-1.0.2/lib/quiet_assets.rb:18:in `call_with_quiet_assets'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_dispatch/middleware/request_id.rb:22:in `call'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/rack-1.4.5/lib/rack/methodoverride.rb:21:in `call'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/rack-1.4.5/lib/rack/runtime.rb:17:in `call'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.17/lib/active_support/cache/strategy/local_cache.rb:72:in `call'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/rack-1.4.5/lib/rack/lock.rb:15:in `call'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/rack-ssl-1.3.4/lib/rack/ssl.rb:27:in `call'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/rack-cache-1.2/lib/rack/cache/context.rb:136:in `forward'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/rack-cache-1.2/lib/rack/cache/context.rb:143:in `pass'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/rack-cache-1.2/lib/rack/cache/context.rb:155:in `invalidate'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/rack-cache-1.2/lib/rack/cache/context.rb:71:in `call!'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/rack-cache-1.2/lib/rack/cache/context.rb:51:in `call'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/railties-3.2.17/lib/rails/engine.rb:484:in `call'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/railties-3.2.17/lib/rails/application.rb:231:in `call'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/railties-3.2.17/lib/rails/railtie/configurable.rb:30:in `method_missing'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/unicorn-4.8.3/lib/unicorn/http_server.rb:576:in `process_client'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/unicorn-4.8.3/lib/unicorn/http_server.rb:670:in `worker_loop'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/unicorn-4.8.3/lib/unicorn/http_server.rb:525:in `spawn_missing_workers'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/unicorn-4.8.3/lib/unicorn/http_server.rb:140:in `start'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/gems/unicorn-4.8.3/bin/unicorn_rails:209:in `<top (required)>'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/bin/unicorn_rails:23:in `load'
  /home/ostaccounts/src/accounts-61f3c16/vendor/bundle/ruby/1.9.1/bin/unicorn_rails:23:in `<main>'
```

**Comment by karenc** [comment]
This is from actionpack-3.2.17/lib/action_dispatch/http/parameter_filter.rb:

```
 25       def compiled_filter         
 26         @compiled_filter ||= begin        
 27           regexps, blocks = compile_filter
 28                                      
 29           lambda do |original_params|
 30             filtered_params = {}
 31                                                 
 32             original_params.each do |key, value|
 33               if regexps.find { |r| key =~ r }
 34                 value = FILTERED     
 35               elsif value.is_a?(Hash)
 36                 value = filter(value) 
 37               elsif value.is_a?(Array)                                 
 38                 value = value.map { |v| v.is_a?(Hash) ? filter(v) : v }
 39               elsif blocks.present?
 40                 key = key.dup                         
 41                 value = value.dup if value.duplicable?
 42                 blocks.each { |b| b.call(key, value) }
 43               end
 44                                           
 45               filtered_params[key] = value
 46             end
 47                            
 48             filtered_params
 49           end
 50         end
 51       end
```

This means one of the keys in the original params is a symbol?

I looked at the email and params is ```Parameters : {"utf8"=>"✓", "authenticity_token"=>"[FILTERED]", "contact_info"=>{"type"=>"EmailAddress", "value"=>"xxx@gmail.com"}, "commit"=>"Add Email address", "action"=>"create", "controller"=>"contact_infos"}```.  Looks ok to me and I can't reproduce the error locally. (I logged in and added an email address for my user)

@jpslav? @Dantemss?

**Comment by Dantemss** [comment]
The real issue is down below on the stack trace. Lev tried to set the transaction isolation level, but Postgres had already aborted the transaction. Not sure how, since the code that calls lev is in a before_save and there's nothing else happening before that save as far as I know.

`ActionView::Template::Error: can't dup Symbol` was apparently another error generated while trying to filter the params to send the exception email.

**Comment by Dantemss** [comment]
The `add_unread_update` code needs some cleanup anyway...

**Comment by karenc** [comment]
Ok this is the actual relevant backtrace...

```
  vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.17/lib/active_record/connection_adapters/postgresql_adapter.rb:650:in `async_exec'
  vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.17/lib/active_record/connection_adapters/postgresql_adapter.rb:650:in `block in execute'
  vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.17/lib/active_record/connection_adapters/abstract_adapter.rb:280:in `block in log'
  vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.17/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.17/lib/active_record/connection_adapters/abstract_adapter.rb:275:in `log'
  vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.17/lib/active_record/connection_adapters/postgresql_adapter.rb:649:in `execute'
  vendor/bundle/ruby/1.9.1/gems/transaction_isolation-1.0.3/lib/transaction_isolation/active_record/connection_adapters/postgresql_adapter.rb:51:in `ensure in isolation_level'
  vendor/bundle/ruby/1.9.1/gems/transaction_isolation-1.0.3/lib/transaction_isolation/active_record/connection_adapters/postgresql_adapter.rb:51:in `isolation_level'
  vendor/bundle/ruby/1.9.1/gems/transaction_isolation-1.0.3/lib/transaction_isolation/active_record/base.rb:7:in `isolation_level'
  vendor/bundle/ruby/1.9.1/gems/lev-2.0.5/lib/lev/routine.rb:394:in `in_transaction'
  vendor/bundle/ruby/1.9.1/gems/lev-2.0.5/lib/lev/routine.rb:236:in `call'
  vendor/bundle/ruby/1.9.1/gems/lev-2.0.5/lib/lev/routine.rb:200:in `call'
  app/models/user.rb:119:in `add_unread_update'
  app/models/contact_info.rb:33:in `add_unread_update'
```

There's nothing we can do about the error in parameter_filter since it's not really our code.

I think this error is potentially a glitch?  May be we were updating the server or something?

Can open a new issue on cleaning up `add_unread_update`.

**Comment by Dantemss** [comment]
Haven't seen this happen again since flow changes.
