### ISSUE TITLE
[Accounts] (prodtutor) sessions#callback (PG::UniqueViolation)  "ERROR: duplicate key value violates unique constraint \...

### ISSUE THREAD

**Issue by Dantemss** [openstax/accounts#308]
```
A PG::UniqueViolation occurred in sessions#callback:

  ERROR:  duplicate key value violates unique constraint "index_authentications_on_user_id_scoped"
DETAIL:  Key (user_id, provider)=(10131, google_oauth2) already exists.

  vendor/bundle/ruby/2.2.0/gems/activerecord-3.2.22/lib/active_record/connection_adapters/postgresql_adapter.rb:1163:in `async_exec'
```

First app line in the backtrace is:

```
app/routines/transfer_authentications.rb:13:in `block in exec'
```

Need to check for duplicate authentications before transferring them in https://github.com/openstax/accounts/blob/master/app/routines/transfer_authentications.rb

**Comment by Dantemss** [comment]
My guess is that if a duplicate authentication is found, leave it there and don't transfer anything. Maybe even delete the one being transferred.

**Comment by Dantemss** [comment]
A full solution will involve https://github.com/openstax/accounts/pull/145
